# Generated by Django 5.2.4 on 2025-07-09 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.TextField()),
                ('player_count', models.CharField(max_length=50)),
                ('playtime', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='games/')),
                ('rules_pdf', models.FileField(upload_to='rules/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
