# Generated by Django 5.2.4 on 2025-07-09 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_game_age_remove_game_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(upload_to='games/'),
        ),
    ]
